apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sidecar-injector-certs
  namespace: default
spec:
  secretName: sidecar-injector-certs
  dnsNames:
    - raycluster-mutating-webhook.default.svc
    - raycluster-mutating-webhook.default.svc.cluster.local
    - raycluster-mutating-webhook.codeflare.com
  issuerRef:
    name: selfsigned-issuer

