apiVersion: v1
kind: ServiceAccount
metadata:
  name: raycluster-mutating-webhook
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raycluster-mutating-webhook
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["ray.io"]
    resources: ["rayclusters"]
    verbs: ["get", "watch", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: raycluster-mutating-webhook
subjects:
  - kind: ServiceAccount
    name: raycluster-mutating-webhook
    namespace: default
roleRef:
  kind: ClusterRole
  name: raycluster-mutating-webhook
  apiGroup: rbac.authorization.k8s.io
