apiVersion: v1
kind: Service
metadata:
  name: raycluster-mutating-webhook
  namespace: default
spec:
  selector:
    app: raycluster-mutating-webhook
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics
